# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormHello.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormHello(object):
    def setupUi(self, FormHello):
        FormHello.setObjectName("FormHello")
        FormHello.resize(591, 386)
        self.frame = QtWidgets.QFrame(FormHello)
        self.frame.setGeometry(QtCore.QRect(70, 90, 421, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LabHello = QtWidgets.QLabel(self.frame)
        self.LabHello.setGeometry(QtCore.QRect(110, 60, 191, 21))
        self.LabHello.setAlignment(QtCore.Qt.AlignCenter)
        self.LabHello.setObjectName("LabHello")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(170, 140, 75, 23))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(FormHello)
        QtCore.QMetaObject.connectSlotsByName(FormHello)

    def retranslateUi(self, FormHello):
        _translate = QtCore.QCoreApplication.translate
        FormHello.setWindowTitle(_translate("FormHello", "Demo2_2"))
        self.LabHello.setText(_translate("FormHello", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">Hello， by UI Designer</span></p></body></html>"))
        self.btnClose.setText(_translate("FormHello", "关闭"))
